---
- hosts: all
  user: orenault
  sudo: yes
  roles:
    - prep
    - ambari-agent
    - users
    - krb-client

- hosts: kdc_server
  user: orenault
  sudo: yes
  roles:
    - kdc

- hosts: db_server
  user: orenault
  sudo: yes
  roles:
    - db-server

- hosts: ambari_server
  user: orenault
  sudo: yes
  roles:
    - ambari-server
    - ambari-kerberos-setup

